import {parseIreal} from './public/ireal.js';
import http from 'node:http';
import {readFile,writeFile,readdir,mkdir,rename,unlink} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import YAML from 'yaml';
import {createMetadataService} from './metadata.mjs';
const metadata=createMetadataService();
import {createChordImportService} from './chord-import.mjs';
const importChords=createChordImportService();
import {youtubeVideoId} from './public/youtube.js';
import {chordSections,inferLoop} from './public/chords.js';
const root=path.dirname(fileURLToPath(import.meta.url));
const data=process.env.DATA_DIR||path.join(root,'data');
await mkdir(path.join(data,'songs'),{recursive:true});
const port=Number(process.env.PORT||4317);
export function parseSong(text,id){const match=text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);if(!match)throw Error('En-tête Markdown manquant');const song={...YAML.parse(match[1]),id,lyrics:match[2].trim()};return {...song,loop:inferLoop(song).loop};}
export function validateSong(s){if(!s||typeof s.title!=='string'||!s.title.trim()||typeof s.artist!=='string'||!s.artist.trim())throw Error('Titre et artiste requis.');if(s.year!==null&&(!Number.isInteger(s.year)||s.year<1900||s.year>2100))throw Error('Année invalide.');if(s.lyricsUrl&&!/^https?:\/\//i.test(s.lyricsUrl))throw Error('Le lien doit commencer par https:// ou http://.');for(const key of ['style','note','lyrics','lyricsUrl'])if(typeof s[key]!=='string')throw Error('Champ invalide : '+key);if(!Number.isInteger(s.decade)||s.decade<1900||s.decade>2100||s.decade%10)throw Error('Décennie invalide.');if(s.youtubeUrl!==undefined&&(typeof s.youtubeUrl!=='string'||(s.youtubeUrl.trim()&&!youtubeVideoId(s.youtubeUrl))))throw Error('Colle un lien vers une vidéo YouTube valide.');if(s.irealUrl!==undefined&&typeof s.irealUrl!=='string')throw Error('Champ invalide : irealUrl');if(s.chords!==undefined&&typeof s.chords!=='string')throw Error('Champ invalide : chords');const irealUrl=(s.irealUrl||'').trim();if(irealUrl)parseIreal(irealUrl);const sections={};for(const [key] of chordSections){if(s[key]!==undefined&&typeof s[key]!=='string')throw Error('Champ invalide : '+key);sections[key]=(s[key]||'').trim();}return {...sections,irealUrl,youtubeUrl:(s.youtubeUrl||'').trim(),title:s.title.trim(),artist:s.artist.trim(),year:s.year,decade:s.year?Math.floor(s.year/10)*10:s.decade,style:s.style.trim(),loop:inferLoop({...sections,irealUrl}).loop,...(s.chords?.trim()?{chords:s.chords.trim()}:{}),note:s.note,lyricsUrl:s.lyricsUrl,lyrics:s.lyrics};}
const safeId=id=>typeof id==='string'&&/^[a-z0-9-]{1,100}$/.test(id);
async function songs(){return Promise.all((await readdir(path.join(data,'songs'))).filter(f=>f.endsWith('.md')).sort().map(async f=>parseSong(await readFile(path.join(data,'songs',f),'utf8'),f.slice(0,-3))));}
async function sets(){try{return JSON.parse(await readFile(path.join(data,'setlists.json'),'utf8'));}catch(e){if(e.code==='ENOENT')return [];throw e;}}
async function atomic(file,content){const tmp=file+'.tmp';await writeFile(tmp,content);await rename(tmp,file);}
let queue=Promise.resolve();
const server=http.createServer(async(req,res)=>{const send=(status,obj)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(obj));};try{const url=new URL(req.url,'http://localhost');if(req.headers.host!==`localhost:${port}`&&req.headers.host!==`127.0.0.1:${port}`)return send(403,{error:'Hôte refusé'});if(req.method==='GET'&&url.pathname==='/api/metadata/search')return send(200,await metadata.search(url.searchParams));if(req.method==='GET'&&url.pathname==='/api/metadata/lyrics')return send(200,await metadata.lyrics(url.searchParams));if(req.method==='GET'&&url.pathname==='/api/chords/import')return send(200,await importChords(url.searchParams.get('url')));if(req.method==='GET'&&url.pathname==='/api/library')return send(200,{songs:await songs(),setlists:await sets()});if(req.method==='DELETE'&&/^\/api\/songs\/[^/]+$/.test(url.pathname)){
if(req.headers.origin&&!['http://localhost:'+port,'http://127.0.0.1:'+port].includes(req.headers.origin))return send(403,{error:'Origine refusée'});
const id=url.pathname.split('/').pop();if(!safeId(id))return send(400,{error:'Identifiant invalide'});
const work=async()=>{const file=path.join(data,'songs',id+'.md');await readFile(file);const previous=await sets();const next=previous.map(s=>({...s,songIds:s.songIds.filter(songId=>songId!==id)}));const setFile=path.join(data,'setlists.json');await atomic(setFile,JSON.stringify(next,null,2)+'\n');try{await unlink(file);}catch(e){await atomic(setFile,JSON.stringify(previous,null,2)+'\n');throw e;}return {id,setlists:next};};
const pending=queue.then(work);queue=pending.catch(()=>{});return send(200,await pending);
}if(req.method==='PUT'&&url.pathname.startsWith('/api/')){if(req.headers.origin&&!['http://localhost:'+port,'http://127.0.0.1:'+port].includes(req.headers.origin))return send(403,{error:'Origine refusée'});if(!req.headers['content-type']?.startsWith('application/json'))return send(415,{error:'JSON requis'});let body='';for await(const chunk of req){body+=chunk;if(body.length>2_000_000)return send(413,{error:'Contenu trop volumineux'});}const input=JSON.parse(body);const work=async()=>{if(url.pathname==='/api/setlists'){const ids=new Set((await songs()).map(s=>s.id));if(!Array.isArray(input)||input.some(s=>!safeId(s.id)||typeof s.name!=='string'||!s.name.trim()||!Array.isArray(s.songIds)||new Set(s.songIds).size!==s.songIds.length||s.songIds.some(id=>!ids.has(id)))||new Set(input.map(s=>s.id)).size!==input.length)throw Error('Setlists invalides');await atomic(path.join(data,'setlists.json'),JSON.stringify(input,null,2)+'\n');return input;}const id=url.pathname.split('/').pop();if(!safeId(id))throw Error('Identifiant invalide');const s=validateSong(input);const {lyrics,...meta}=s;await atomic(path.join(data,'songs',id+'.md'),'---\n'+YAML.stringify(meta)+'---\n\n'+lyrics+'\n');return {...s,id};};const pending=queue.then(work);queue=pending.catch(()=>{});return send(200,await pending);}
if(req.method!=='GET')return send(405,{error:'Méthode non autorisée'});
const vendors={'/vendor/marked.js':'node_modules/marked/lib/marked.esm.js','/vendor/purify.js':'node_modules/dompurify/dist/purify.es.mjs'};const relative=vendors[url.pathname]||'public/'+(url.pathname==='/'?'index.html':url.pathname.slice(1));const file=path.resolve(root,relative);if(!file.startsWith(path.join(root,'public')+path.sep)&&!vendors[url.pathname])return send(403,{error:'Accès refusé'});const content=await readFile(file);res.writeHead(200,{'Content-Type':({'html':'text/html','css':'text/css','js':'text/javascript','mjs':'text/javascript','svg':'image/svg+xml'})[file.split('.').pop()]||'application/octet-stream','Cache-Control':'no-cache'});res.end(content);
}catch(e){send(e.code==='ENOENT'?404:400,{error:e.message});}});
if(process.argv[1]===fileURLToPath(import.meta.url))server.listen(port,'127.0.0.1',()=>console.log(`Playlist Jam : http://localhost:${port}`));
