import {test,expect} from '@playwright/test';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
let dir,server;
const first='Session <acoustique>',second='Une longue playlist pour les répétitions du dimanche';
test.beforeAll(async()=>{
  dir=await mkdtemp(path.join(os.tmpdir(),'playlist-memberships-'));
  await mkdir(path.join(dir,'songs'));
  for(const [id,title] of [['song-a','Morceau A'],['song-b','Morceau B']])await writeFile(path.join(dir,'songs',id+'.md'),`---\ntitle: ${title}\nartist: Artiste test\nyear: 2020\ndecade: 2020\nstyle: Pop\nloop: yes\nchords: C - G\nnote: ""\nlyricsUrl: ""\n---\n\nTexte personnel.\n`);
  await writeFile(path.join(dir,'setlists.json'),JSON.stringify([{id:'set-a',name:first,songIds:['song-b','song-a']},{id:'set-b',name:second,songIds:['song-a']}]));
  server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'4320',DATA_DIR:dir},stdio:'pipe'});
  await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(Error('Server exited: '+code)));});
});
test.afterAll(async()=>{server?.kill();await rm(dir,{recursive:true,force:true});});
test('playlist tags, targeted removal, persistence, failure and mobile',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:4320');
  const row=page.locator('tr[data-id="song-a"]');
  await expect(row.locator('.playlist-tag')).toHaveCount(2);
  await expect(row.locator('.playlist-tag').first()).toContainText(first);
  await row.locator('input[type=checkbox]').check();
  await page.locator('#search').fill('Morceau A');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'/tmp/playlist-memberships-mobile.png',fullPage:true});
  await page.emulateMedia({media:'print'});
  await expect(row.locator('.playlist-remove').first()).toBeHidden();
  await expect(row.locator('.playlist-tag').first()).toBeVisible();
  await page.emulateMedia({media:'screen'});
  await row.getByRole('button',{name:'Retirer Morceau A de '+first,exact:true}).click();
  await expect(row.locator('.playlist-tag')).toHaveCount(1);
  await expect(row.locator('input[type=checkbox]')).toBeChecked();
  await expect(page.locator('#song-dialog')).not.toBeVisible();
  await expect(page.locator('#search')).toHaveValue('Morceau A');
  let sets=JSON.parse(await readFile(path.join(dir,'setlists.json'),'utf8'));
  expect(sets.map(s=>s.songIds)).toEqual([['song-b'],['song-a']]);
  await page.reload();
  await expect(page.locator('#rows tr')).toHaveCount(2);
  await expect(row.locator('.playlist-tag')).toHaveCount(1);
  await page.route('**/api/setlists',route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Échec de sauvegarde simulé'})}));
  const remove=row.getByRole('button',{name:'Retirer Morceau A de '+second,exact:true});
  await remove.click();
  await expect(page.locator('#toast')).toHaveText('Échec de sauvegarde simulé');
  await expect(row.locator('.playlist-tag')).toHaveCount(1);
  await expect(remove).toBeEnabled();
  await page.unroute('**/api/setlists');
  await remove.focus();await page.keyboard.press('Enter');
  await expect(row.locator('.playlist-tag')).toHaveCount(0);
  await expect(row.locator('[data-open]')).toBeFocused();
  sets=JSON.parse(await readFile(path.join(dir,'setlists.json'),'utf8'));
  expect(sets.map(s=>s.songIds)).toEqual([['song-b'],[]]);
  await page.locator('[data-view="set-b"]').click();
  await expect(page.locator('#rows tr')).toHaveCount(0);
  await page.locator('#library').click();
  await expect(page.locator('#rows tr')).toHaveCount(2);
  await expect(page.locator('tr[data-id="song-b"] .playlist-tag')).toHaveCount(1);
  expect(errors).toEqual([]);
});
